baseURL = 'donguri-wind.442hz.tokyo'
languageCode = 'ja'
languageName = 'Japanese'
# defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'どんぐりの吹奏楽団'

[module]
[[module.imports]]
path = "github.com/willfaught/paige"


[paige]
color = "#0d6efd" # Bootstrap primary color and theme color for Safari and Windows
color_scheme = "auto" # Must be "auto", "dark", or "light"
external_link_new_tab = false # Open external links in new tabs
math = false # Enable math typesetting
site_title = "" # Appears above the menu, above the site description, if set
site_description = "" # Appears above the menu, below the site title, if set
style = "" # CSS included at the end of the stylesheet, before style-last.css

[paige.analytics]
disable = false # Disable all analytics

[paige.analytics.beam] # See https://beamanalytics.io
token = ""

[paige.analytics.chartbeat] # See https://chartbeat.com
account_id = ""
domain = ""

[paige.analytics.clarity] # See https://clarity.microsoft.com
account_id = ""

[paige.analytics.clicky] # See https://clicky.com
account_id = ""

[paige.analytics.counter] # See https://counter.dev
account_id = ""
utc_offset = ""

[paige.analytics.fathom] # See https://usefathom.com
account_id = ""

[paige.analytics.finteza] # See https://finteza.com
account_id = ""
script_url = ""

[paige.analytics.hotjar] # See https://hotjar.com
account_id = ""

[paige.analytics.matomo] # See https://matomo.org
account_id = ""
host_url = ""

[paige.analytics.mixpanel] # See https://mixpanel.com
token = ""

[paige.analytics.pirsch] # See https://pirsch.io
identification_code = ""

[paige.analytics.plausible] # See https://plausible.io
account_id = ""

[paige.analytics.woopra] # See https://woopra.com
domain = ""

[paige.analytics.yandex] # See https://metrica.yandex.com
account_id = ""

[paige.comments]
disable = false # Disable all comments

[paige.comments.cactus] # See https://cactus.chat
account_id = ""

[paige.comments.commento] # See https://commento.io
script_url = ""

[paige.comments.graphcomment] # See https://graphcomment.com
account_id = ""

[paige.comments.hyvor] # See https://hyvor.com
account_id = ""

[paige.comments.intensedebate] # See https://intensedebate.com
account_id = ""

[paige.comments.isso] # See https://isso-comments.de
script_url = ""

[paige.comments.remark42] # See https://remark42.com
host_url = ""
site_id = ""

[paige.comments.replybox] # See https://getreplybox.com
account_id = ""

[paige.comments.utterances] # See https://utteranc.es
github_repo = ""

[paige.date]
format = ":date_long" # Hugo date format

[paige.feed]
hide_page = false
link_to_page = false # Link to the page instead of the front matter link, if present
page_link = "⏎" # If a front matter link is present, and link_to_page is false, then link to the page with this text

[paige.feed.atom]
authors = []
# Example is:
# [[paige.feed.atom.authors]]
# email = "will.faught@example.com"
# name = "Will Faught
# url = "https://github.com/willfaught/paige"
icon = "" # Example is "/icon.webp"
logo = "" # Example is "/logo.webp"

[paige.feed.rss]
managing_editor = "" # Example is "will.faught@example.com (Will Faught)"
web_master = "" # Example is "will.faught@example.com (Will Faught)"

[paige.file_link] # A link placed at the top of the footer for pages with files
content = "" # Example is "Edit this page"
disable = false
url = ""
# The formatting verb "%s" is replaced with the path to the file relative to the content directory.
# Example is "https://github.com/willfaught/paige/edit/master/content/%s".

[paige.git]
commit_url = "" # Example is "https://github.com/willfaught/paige/commit/%s"

[paige.menu]
style = "links" # Must be "links", "pills", "tabs", or "underline"

[paige.search]
hide_page = false




[languages.en]
weight = 10

[[languages.en.menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 20

[[languages.en.menu.main]]
identifier = "life"
name = "Life"
parent = "blog"
url = "/blog/life/"
weight = 10

[[languages.en.menu.main]]
identifier = "work"
name = "Work"
parent = "blog"
url = "/blog/work/"
weight = 20

[languages.en.menu.main.params.paige]
divider_below = true

[[languages.en.menu.main]]
identifier = "interests"
name = "Interests"
parent = "blog"
url = "/blog/interests/"
weight = 30

[languages.en.menu.main.params.paige]
disabled = true

[[languages.en.menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 30

[[languages.en.menu.main]]
identifier = "search"
name = "Search"
url = "/search/"
weight = 40